name: api_response_log
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter_json_view: ^1.1.4
  diacritic: ^0.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
